resolver: lts-9.6
packages:
- '.'
extra-deps:
system-ghc: false
docker:
  enable: true
nix:
  enable: false
  pure: false

image:
  container:
    executables: [txtchat]
    name: andgate/txtchat
    base: fpco/stack-run
